### PR TITLE
added logo

### LINKED ISSUE #22: Make and add logo in README.md
# Description

Create a logo with some mice and demons in a cartoon/anime like style.
* One idea is to have the first layer with some mice and then another one (behind them) with some dragons. The Dragons would look bigger than the mice.
* And probably the logo somewhere up

### PR DESCRIPTION
**Pull request by vanntile**
closes #22 

The assets have been put into the `res` folder.

Licensing details:
- the dragon icon is free, under the attribution license from freepik
  - `Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a>`
- the mouse icon is under the GitHub Student Developer Pack Icon8 account license to the associated GitHub account of @vanntile 

I recommend having a `LICENSE.md` file with these details, or an `ACKNOWLEDGEMENTS`

### CODE REVIEW

**Comment by gmuraru** [comment]
There is a commit linter. You might want to use this https://commitlint.io/ or a cli tool (that's what I am using).

**Comment by vanntile** [comment]
> There is a commit linter. You might want to use this https://commitlint.io/ or a cli tool (that's what I am using).

Yeah, I'm used to less-tight linting rules. (Emoji ftw)

**Comment by vanntile** [comment]
Closes #22

**Comment by gmuraru** [comment]
Great! Thank you :100:

**Pull request merged**
